name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  ANDROID_CWD: platforms/mobile/android/

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install SSH key for Design System
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519_design_system # optional
          known_hosts: "|1|r2GtBiIWDfKxTeQNSzBCec0o7aY=|JucDoGUfPPyGD2WdSLxbN5EmiLE= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
          config: |
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519_design_system

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter @redinn/oceanpeace-mobile sync

      - name: Build AAP
        working-directory: ${{ env.ANDROID_CWD }}
        run: gradle bundle

      - name: Build APK
        working-directory: ${{ env.ANDROID_CWD }}
        run: gradle assembleRelease

      - name: Android Sign APK
        uses: ilharp/sign-android-release@v1 # Or use @nightly
        id: sign_apk
        with:
          releaseDir: ${{ env.ANDROID_CWD }}app/build/outputs/apk/release
          signingKey: ${{ secrets.RELEASE_KEYSTORE }}
          keyAlias: release
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: ${{steps.sign_apk.outputs.signedFile}}
          retention-days: 60

      - name: Android Sign AAP
        uses: ilharp/sign-android-release@v1 # Or use @nightly
        id: sign_aap
        with:
          releaseDir: ${{ env.ANDROID_CWD }}app/build/outputs/bundle/release
          signingKey: ${{ secrets.RELEASE_KEYSTORE }}
          keyAlias: release
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - name: Upload AAP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AAP
          path: ${{steps.sign_aap.outputs.signedFile}}
          retention-days: 60
