name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install SSH key for Design System
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519_design_system # optional
          known_hosts: "|1|r2GtBiIWDfKxTeQNSzBCec0o7aY=|JucDoGUfPPyGD2WdSLxbN5EmiLE= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
          config: |
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519_design_system

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter @redinn/oceanpeace-mobile sync

      - name: Build app bundle
        run: cd platforms/mobile/android/ && gradle bundle

      - name: Extract Android signing key from env
        run: |
          cd platforms/mobile/
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign AAP
        run: cd platforms/mobile/ && jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: Android App Bundle
          path: platforms/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60
