name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = next ]; then
            pnpm lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            pnpm lerna version --conventional-commits --conventional-graduate --yes
          fi
