name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install SSH key for Design System
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519_design_system # optional
          known_hosts: "|1|r2GtBiIWDfKxTeQNSzBCec0o7aY=|JucDoGUfPPyGD2WdSLxbN5EmiLE= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
          config: |
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519_design_system

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = next ]; then
            pnpm lerna version --conventional-commits --conventional-prerelease --preid beta --yes --create-release github
          else
            pnpm lerna version --conventional-commits --yes --create-release github
          fi
